import create from "zustand";

export type DefaultSectors = {
  sectors: string[];
};

export const useDefaultSectors = create<DefaultSectors>(() => ({
  sectors: [
    "24 de Abril",
    "30 de Mayo",
    "Altos De Arroyo Hondo",
    "Arroyo Manzano",
    "Atala",
    "Bella Vista",
    "Buenos Aires",
    "Cacique",
    "Zona Universitaria",
    "Centro de los Heroes",
    "Cerros De Arroyo Hondo",
    "Ciudad Moderna",
    "Ciudad Nueva",
    "Cristo Rey",
    "Dominicanos Ausentes",
    "El Manguito",
    "El Millon",
    "Ensanche Capotillo",
    "Ensanche Espaillat",
    "Ensanche Kennedy",
    "Ensanche La Fé",
    "Ensanche La Paz",
    "Ensanche Luperon",
    "Ensanche Miraflores",
    "Ensanche Naco",
    "Ensanche Paraiso",
    "Ensanche Quisqueya",
    "Ensanche Simon Bolivar",
    "Evaristo Morales",
    "Gala",
    "Gazcue",
    "Gral Antonio Duverge",
    "Guachupita",
    "Gualey",
    "Honduras",
    "Honduras Del Nte",
    "Jardines del Caribe",
    "Jardines del Norte",
    "Julieta Morales",
    "La Agustina",
    "La Esperilla",
    "La Hondonada",
    "La Isabela",
    "La Julia",
    "La Zurza",
    "Las Praderas",
    "Las Villas",
    "Los Cacicazgos",
    "Los Jardines del Sur",
    "Los Peralejos",
    "Los Prados",
    "Los Proceres",
    "Los Restauradores",
    "Los Rios",
    "Maria Auxiliadora",
    "Mata Hambre",
    "Mejoramiento Social",
    "Mirador Norte",
    "Mirador Sur",
    "Miramar",
    "Nuevo Arroyo Hondo",
    "Palma Real",
    "Piantini",
    "Renacimiento",
    "San Carlos",
    "San Geronimo",
    "San Juan Bosco",
    "Viejo Arroyo Hondo",
    "Villa Agricolas",
    "Villa Consuelo",
    "Villa Francisca",
    "Villa Juana",
    "Zona Colonial",
  ],
}));
